name: Check dependencies
on:
  push:
    # paths:
    #   - '**.go'
    branches:
      - main
      - release-*
  pull_request:
    # paths:
    #   - '**.go'
    branches:
      - main
      - release-*

permissions: read-all

jobs:
  check-deps:
    name: "Check dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Go 1.21
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.21"
      - name: Check go.mod
        shell: bash
        run: |
          # there should be no go.mod changes
          go mod tidy
          git diff --exit-code
